In [4]:
import pandas as pd
from pathlib import Path

DATA_DIR = Path("../data/raw/archive")

customers = pd.read_csv(DATA_DIR / "olist_customers_dataset.csv")

customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [5]:
from pathlib import Path

for file in DATA_DIR.glob("*.csv"):
    print(file.name)

olist_customers_dataset.csv
olist_geolocation_dataset.csv
olist_orders_dataset.csv
olist_order_items_dataset.csv
olist_order_payments_dataset.csv
olist_order_reviews_dataset.csv
olist_products_dataset.csv
olist_sellers_dataset.csv
product_category_name_translation.csv

In [6]:
files = list(DATA_DIR.glob("*.csv"))

print(f"Number of datasets: {len(files)}")

Number of datasets: 9

In [7]:
from pathlib import Path
import pandas as pd

DATA_DIR = Path("../data/raw/archive")

datasets = {}

for file in DATA_DIR.glob("*.csv"):
    datasets[file.stem] = pd.read_csv(file)

print(f"Loaded {len(datasets)} datasets")

Loaded 9 datasets

In [8]:
datasets.keys()

dict_keys(['olist_customers_dataset', 'olist_geolocation_dataset', 'olist_orders_dataset', 'olist_order_items_dataset', 'olist_order_payments_dataset', 'olist_order_reviews_dataset', 'olist_products_dataset', 'olist_sellers_dataset', 'product_category_name_translation'])

In [9]:
inventory = []

for name, df in datasets.items():
    inventory.append({
        "table": name,
        "rows": df.shape[0],
        "columns": df.shape[1]
    })

inventory = pd.DataFrame(inventory)
inventory.sort_values("table")

                               table     rows  columns
0            olist_customers_dataset    99441        5
1          olist_geolocation_dataset  1000163        5
3          olist_order_items_dataset   112650        7
4       olist_order_payments_dataset   103886        5
5        olist_order_reviews_dataset    99224        7
2               olist_orders_dataset    99441        8
6             olist_products_dataset    32951        9
7              olist_sellers_dataset     3095        4
8  product_category_name_translation       71        2

In [11]:
inventory.to_markdown("../docs/data_inventory.md", index=False)